[package]
name = "neko_ai"
version = "0.0.2-alpha"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
config = "0.15.19"
dotenvy = "0.15.7"
poise = "0.6.1"
rig-core = { version = "0.31.0", features = ["image", "derive"]}
rig-qdrant = "0.1.37"
serenity = { version = "0.12.5", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
qdrant-client = "1.17.0"
tokio = { version = "1.49.0", features = ["full"] }
tonic = "0.14.5"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
uuid = { version = "1.21.0", features = ["v4"]}
