[nlp]
api_url = "https://openrouter.ai/api/v1"
model_name="arcee-ai/trinity-large-preview:free"
max_short_term_messages = 20

[embedding]
api_url = "https://openrouter.ai/api/v1"
model_name = "openai/text-embedding-3-small"