[nlp]
api_url = "https://openrouter.ai/api/v1"
model_name="qwen/qwen3-vl-235b-a22b-thinking"
max_short_term_messages = 20

[embedding]
api_url = "https://openrouter.ai/api/v1"
model_name = "openai/text-embedding-3-small"
dimension = 1536