[nlp]
api_url = "https://openrouter.ai/api/v1"
model_name="nvidia/nemotron-3-nano-30b-a3b:free"
max_short_term_messages = 20

[embedding]
api_url = "https://openrouter.ai/api/v1"
model_name = "openai/text-embedding-3-small"