[nlp]
api_url = "https://openrouter.ai/api/v1"
model_name="stepfun/step-3.5-flash:free"
max_short_term_messages = 20

[embedding]
api_url = "https://openrouter.ai/api/v1"
model_name = "openai/text-embedding-3-small"
dimension = 1536